name: dpr
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - backports.zstd=1.2.0
  - blas=1.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - charset-normalizer=3.4.4
  - cuda-cccl=12.9.27
  - cuda-cccl_win-64=12.9.27
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-opencl-dev=12.9.19
  - cuda-profiler-api=12.9.79
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - faiss=1.8.0
  - faiss-gpu=1.8.0
  - filelock=3.20.1
  - freetype=2.14.1
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.11
  - intel-openmp=2025.3.0
  - jinja2=3.1.6
  - khronos-opencl-icd-loader=2024.10.24
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.25
  - libexpat=2.7.3
  - libfaiss=1.8.0
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libpng=1.6.53
  - libsqlite=3.51.1
  - libtiff=4.7.1
  - libuv=1.51.0
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.16
  - libxml2=2.13.9
  - libzlib=1.3.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=3.0.3
  - mkl=2023.1.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - networkx=3.4.2
  - numpy=1.26.4
  - opencl-headers=2025.06.13
  - openjpeg=2.5.4
  - openssl=3.6.0
  - packaging=25.0
  - pillow=10.4.0
  - pip=25.3
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pysocks=1.7.1
  - python=3.10.19
  - python_abi=3.10
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.3
  - requests=2.32.5
  - setuptools=80.9.0
  - sympy=1.14.0
  - tbb=2021.13.0
  - tk=8.6.13
  - typing_extensions=4.15.0
  - ucrt=10.0.26100.0
  - urllib3=2.6.2
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - yaml=0.2.5
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anyio==4.12.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.4.0
      - colorama==0.4.6
      - datasets==4.4.2
      - dill==0.4.0
      - dm-tree==0.1.9
      - docstring-parser==0.17.0
      - einops==0.8.1
      - etils==1.13.0
      - exceptiongroup==1.3.1
      - flatbuffers==25.12.19
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gast==0.7.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - immutabledict==4.2.2
      - importlib-resources==6.5.2
      - keras==3.12.0
      - libclang==18.1.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - multidict==6.7.0
      - multiprocess==0.70.18
      - namex==0.1.0
      - npy-append-array==0.9.19
      - opt-einsum==3.4.0
      - optree==0.18.0
      - pandas==2.3.3
      - promise==2.3
      - propcache==0.4.1
      - protobuf==4.21.12
      - psutil==7.2.0
      - pyarrow==22.0.0
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - regex==2025.11.3
      - rich==14.2.0
      - safetensors==0.7.0
      - sentencepiece==0.2.1
      - simple-parsing==0.1.7
      - six==1.17.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.1
      - tensorflow-datasets==4.9.9
      - tensorflow-io-gcs-filesystem==0.31.0
      - tensorflow-metadata==1.17.2
      - termcolor==3.2.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - torch==2.11.0.dev20251224+cu128
      - torchaudio==2.10.0.dev20251224+cu128
      - torchvision==0.25.0.dev20251224+cu128
      - tqdm==4.67.1
      - transformers==4.57.3
      - tzdata==2025.3
      - werkzeug==3.1.4
      - wget==3.2
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: C:\Users\iksdg\miniforge3\envs\dpr
